Controllers/PronosticosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mundial2022.Entidades;
using Mundial2022.Modelos;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Mundial2022.Controllers
{
    public class PronosticosController : Controller
    {
        private readonly MundialClubesContext context;

        public PronosticosController(MundialClubesContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index(Usuario usuario)
        {
            return View(usuario);
        }

        public IActionResult Crear(int Id)
        {
            PronosticoCreacionViewModel pronostico = new PronosticoCreacionViewModel();
            
            pronostico.UserId = Id;
            pronostico.FasesSelect = context.Fases.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
            pronostico.GruposSelect = pronostico.Grupos.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
            pronostico.partidos = context.Partidos.Include(e => e.CEquipo1Navigation).Include(e => e.CEquipo2Navigation);
            return View(pronostico);

        }

        [HttpPost]
        public IActionResult Crear(IFormCollection formCollection)
        {
            string uCodigo = "656";
            IEnumerable<string> numerosPartidos = formCollection["NroPartido"];
            IEnumerable<string> codigosEquipo1Partidos = formCollection["CEquipo1"];
            IEnumerable<string> golesEquipo1Partidos = formCollection["QGolesE1"];
            IEnumerable<string> golesEquipo2Partidos = formCollection["QGolesE2"];

            List<ApuestasUsuario> apuestas = new List<ApuestasUsuario>();
            for (int i = 0; i < numerosPartidos.Count(); i++)
            {
                apuestas.Add(new ApuestasUsuario
                {
                    NroApuetas = numerosPartidos.ToString().ElementAt(i),
                    NroPartido = int.Parse(numerosPartidos.ElementAt(i)),
                    UCodigo = uCodigo,
                    AResultadoE1 = int.Parse(golesEquipo1Partidos.ElementAt(i)),
                    AResultadoE2 = int.Parse(golesEquipo2Partidos.ElementAt(i))
                });
            }

            foreach (var apuesta in apuestas)
            {
                try
                {
                    context.ApuestasUsuarios.Add(apuesta);
                }
                catch (Exception ex)
                {
                    string exs = ex.ToString();
                }
            }
            context.SaveChanges();
            return Ok();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mundial2022</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Pronósticos</a>
                        </li>
@*                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pronosticos" asp-action="Crear">Registrar pronostico</a>
                        </li>*@
                    </ul>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mundial2022 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LinksLogin.cshtml
<ul class="navbar-nav">
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @ViewBag.nombreUsuario</span>
        </li>
        <li class="nav-item">
            <form class="form-check-inline" asp-action="LogOut" asp-controller="Usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
</ul>